#
#	 eapol_test -c peap-mschapv2.conf -s localhostradiussecret
#
network={
	ssid="example"
	eap=PEAP
	key_mgmt=WPA-EAP
	identity="testuser"
	anonymous_identity="monitoring"
	password="passwordoftestuser"
	phase2="autheap=MSCHAPv2"
	domain_suffix_match="expected.radius.domain.example.com"
	ca_path="/etc/ssl/certs"
}

